services:
    App\IdentityAccess\Application\Port\PasswordHashingPort:
        alias: App\IdentityAccess\Adapter\Security\SymfonyPasswordHasher
        public: true

    App\Tests\Fixture\Http\HttpInfrastructureController:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']
