framework:
    rate_limiter:
        registration_ip:
            policy: sliding_window
            limit: 5
            interval: '1 hour'
            cache_pool: cache.rate_limiter
        registration_email:
            policy: sliding_window
            limit: 3
            interval: '24 hours'
            cache_pool: cache.rate_limiter
        activation_ip:
            policy: sliding_window
            limit: 10
            interval: '15 minutes'
            cache_pool: cache.rate_limiter
        activation_token:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'
            cache_pool: cache.rate_limiter
